language: csharp
mono: none
dotnet: 2.1
git:
    submodules: true
install:
  - dotnet restore
script:
  - dotnet build ./Quaver
after_success:
 - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh success $WEBHOOK_URL
after_failure:
 - wget https://raw.githubusercontent.com/Swan/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh failure $WEBHOOK_URL